version: "3.8"

services:
  foundryvtt1:
    environment:
      TIMED_URL: ${TIMED_URL:?err0.1}
    image: rheuvel/repo:foundryvtt-app
    restart: always
    expose:
      - "30000"
    volumes:
      - /usr/share/foundryvtt:/app/foundryvtt
      - /usr/share/foundryshare:/app/foundryshare
      - foundrydata1:/app/foundrydata

  foundryvtt2:
    environment:
      TIMED_URL: ${TIMED_URL:?err0.1}
    image: rheuvel/repo:foundryvtt-app
    restart: always
    expose:
      - "30000"
    volumes:
      - /usr/share/foundryvtt:/app/foundryvtt
      - /usr/share/foundryshare:/app/foundryshare
      - foundrydata2:/app/foundrydata

  foundryvtt3:
    environment:
      TIMED_URL: ${TIMED_URL:?err0.1}
    image: rheuvel/repo:foundryvtt-app
    restart: always
    expose:
      - "30000"
    volumes:
      - /usr/share/foundryvtt:/app/foundryvtt
      - /usr/share/foundryshare:/app/foundryshare
      - foundrydata3:/app/foundrydata

  proxy:
    environment:
      BASE_URL: "${BASE_URL:?err1.1}"
    image: rheuvel/repo:foundryvtt-reverseproxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/share/nginx/certificates:/usr/share/nginx/certificates

  certbot:
    environment:
      DOMAIN: "${BASE_URL:?err2.1}"
      EMAIL: "${CERT_EMAIL:?err2.2}"
      TENANT_ID: "${AZURE_DNS_TENANT_ID:?err2.3}"
      CLIENT_ID: "${AZURE_DNS_CLIENT_ID:?err2.4}"
      CLIENT_SECRET: "${AZURE_DNS_CLIENT_SECRET:?err2.5}"
      DNS_ZONE: "${AZURE_DNS_DNS_ZONE:?err2.6}"
    image: rheuvel/certbot_azure
    restart: always
    volumes:
      - /usr/share/nginx/certificates:/usr/share/nginx/certificates