FROM ubuntu:22.04
RUN mkdir -p /app
WORKDIR /app
RUN apt-get update && apt-get install -y curl wget unzip
#RUN mkdir foundryvtt && mkdir foundrydata
RUN curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh
RUN bash nodesource_setup.sh
RUN  apt-get install -y nodejs

COPY ./FoundryVTT/entrypoint.sh /
RUN ["chmod", "+x", "/entrypoint.sh"]
ENTRYPOINT ["/entrypoint.sh"]