version: "3.6"

services:
  foundryvtt1:
    environment:
      TIMED_URL: ${TIMED_URL:?err0.1}
    image: rheuvel/repo:foundryvtt-app
    restart: always
    expose:
      - "30000"
    volumes:
      - /usr/share/foundryvtt:/app/foundryvtt
      - /usr/share/foundryshare:/app/foundryshare
      - foundrydata1:/app/foundrydata

  foundryvtt2:
    environment:
      TIMED_URL: ${TIMED_URL:?err0.1}
      DELAY: true
    image: rheuvel/repo:foundryvtt-app
    restart: always
    expose:
      - "30000"
    volumes:
      - /usr/share/foundryvtt:/app/foundryvtt
      - /usr/share/foundryshare:/app/foundryshare
      - foundrydata2:/app/foundrydata

  foundryvtt3:
    environment:
      TIMED_URL: ${TIMED_URL:?err0.1}
      DELAY: true
    image: rheuvel/repo:foundryvtt-app
    restart: always
    expose:
      - "30000"
    volumes:
      - /usr/share/foundryvtt:/app/foundryvtt
      - /usr/share/foundryshare:/app/foundryshare
      - foundrydata3:/app/foundrydata

  proxy:
    environment:
      BASE_URL: "${BASE_URL:?err1.1}"
    image: rheuvel/repo:foundryvtt-reverseproxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/share/nginx/certificates:/usr/share/nginx/certificates

  certbot:
    environment:
      - DOMAIN=${BASE_URL}
      - EMAIL=${CERT_EMAIL}
      - TENANT_ID={AZURE_DNS_TENANT_ID}
      - CLIENT_ID={AZURE_DNS_CLIENT_ID}
      - CLIENT_SECRET=${AZURE_DNS_CLIENT_SECRET}
      - DNS_ZONE=${AZURE_DNS_DNS_ZONE}
    image: rheuvel/certbot_azure
    restart: always
    volumes:
      - /usr/share/nginx/certificates:/usr/share/nginx/certificates

volumes:
  foundrydata1:
  foundrydata2:
  foundrydata3: