version: "3.8"

services:
  foundryvtt:
    environment:
      TIMED_URL=${TIMED_URL:?err0.1}
    image: rheuvel/repo:foundryvtt_app
    restart: always
    expose:
      - "30000"
    volumes:
      - /usr/share/foundryvtt:/app/foundryvtt
      - /usr/share/foundrydata:/app/foundrydata

  proxy:
    environment:
      BASE_URL: "${BASE_URL:?err1.1}"
    image: rheuvel/repo:foundryvtt_proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /usr/share/nginx/certificates:/usr/share/nginx/certificates