name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  push-ReverseProxy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.ReverseProxy
          context: ./
          tags: rheuvel/repo:foundryvtt-reverseproxy
          load: true
      - working-directory: ./
        run: docker push rheuvel/repo:foundryvtt-reverseproxy
        
  push-FoundryVTT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v2
        with:
          file: ./Dockerfile.FoundryVTT
          context: ./
          tags: rheuvel/repo:foundryvtt-app
          load: true
      - working-directory: ./
        run: docker push rheuvel/repo:foundryvtt-app
        